### PR TITLE
"Terraform env tfvars created and applied while creating resources"

### PR DESCRIPTION
**Pull request by RameshDevops55**
Terraform env tfvars created and applied while creating resources. this is validated in local env.

### CODE REVIEW

**Review by DivyaMandati — COMMENTED** [review]
env folder is missing

**Comment by RameshDevops55** [comment]
I have added env folder to branch

**Comment by harshini6395** [comment]
Merge into main.

**Comment by RameshDevops55** [comment]
branch code merged to Main

**Pull request merged**
